language: bash
services:
  - docker

before_script:
  - image="djx339/etcd:${VERSION}"

script:
  - docker pull --all-tags quay.io/coreos/etcd

after_success:
  - docker images

# vim:set et ts=2 sw=2:
