language: bash
services:
  - docker

env:
  - VERSION=vlatest
  - VERSION=v3.0.7
  - VERSION=v3.0.6
  - VERSION=v3.0.5
  - VERSION=v3.0.4
  - VERSION=v3.0.3
  - VERSION=v3.0.2
  - VERSION=v3.0.1
  - VERSION=v3.0.0
  - VERSION=v3.0.0-beta.0
  - VERSION=v2.3.7
  - VERSION=v2.3.6
  - VERSION=v2.3.5
  - VERSION=v2.3.4
  - VERSION=v2.3.3
  - VERSION=v2.3.2
  - VERSION=v2.3.1
  - VERSION=v2.3.0
  - VERSION=v2.3.0-alpha.1
  - VERSION=v2.3.0-alpha.0
  - VERSION=v2.2.5
  - VERSION=v2.2.4
  - VERSION=v2.2.3
  - VERSION=v2.2.2
  - VERSION=v2.2.1
  - VERSION=v2.2.0
  - VERSION=v2.2.0-rc.0
  - VERSION=v2.2.0-alpha.1
  - VERSION=v2.2.0-alpha.0
  - VERSION=v2.1.3
  - VERSION=v2.1.2
  - VERSION=v2.1.1
  - VERSION=v2.1.0-rc.0
  - VERSION=v2.1.0-alpha.1
  - VERSION=v2.1.0-alpha.0
  - VERSION=v2.0.13
  - VERSION=v2.0.12
  - VERSION=v2.0.11
  - VERSION=v2.0.10
  - VERSION=v2.0.9
  - VERSION=v2.0.8
  - VERSION=v2.0.7
  - VERSION=v2.0.6
  - VERSION=v2.0.5
  - VERSION=v2.0.4
  - VERSION=v2.0.3
  - VERSION=v2.0.0_rc.1
  - VERSION=v2.0.0


before_script:
  - image="djx339/etcd:${VERSION}"

script:
  - docker pull quay.io/coreos/etcd:${VERSION} 
  - docker tag quay.io/coreos/etcd:${VERSION} ${image}

after_success:
  - docker images
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ${image}



# vim:set et ts=2 sw=2:
